In [3]:
a = [1,2]

In [4]:
a[0] = 3.0

In [5]:
a

[3.0, 2]

In [6]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [10]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [11]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])    #list -> tensor
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[0]

tensor([4., 1.])

In [15]:
points.shape #第0軸: 3維(3個元素)     第1軸: 2維(2個元素)

torch.Size([3, 2])

In [16]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
some_list = list(range(6))     #Note
some_list[:]

[0, 1, 2, 3, 4, 5]

In [20]:
some_list[0:4]

[0, 1, 2, 3]

In [21]:
some_list[1:]

[1, 2, 3, 4, 5]

In [22]:
some_list[:-1]        #Note

[0, 1, 2, 3, 4]

In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
points[0][1]

tensor(1.)

In [26]:
points[0]

tensor([4., 1.])

In [27]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [28]:
points[1:, 0]

tensor([5., 2.])

In [29]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\user\AppData\Local\Temp/ipykernel_13356/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1463.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [31]:
import torch
img_t = torch.randn(3, 5, 5)
batch_t = torch.randn(2, 3, 5, 5)
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')  #若張量超過3個軸, 忽略前面的軸
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns') #未命名的為None
print("img named:", img_named.shape, img_named.names)
print("img named:", batch_named.shape, batch_named.names)
print(img_named)
print(img_t)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
img named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')
tensor([[[-4.6937e-01,  1.8871e-01, -1.8858e-01, -8.7827e-01,  1.4024e+00],
         [ 6.1740e-01, -7.1060e-01,  1.9950e-01,  1.1452e+00,  2.0100e-04],
         [ 1.4875e-01, -2.4577e-01,  1.1530e+00, -9.3789e-01, -2.5231e+00],
         [ 8.5101e-03,  1.1237e-01, -1.9479e+00,  2.7874e-01, -2.5517e+00],
         [ 3.4099e-01,  1.9543e+00,  3.1626e+00,  1.1588e+00, -2.3751e+00]],

        [[-6.8112e-01, -1.7150e+00,  1.6558e+00,  4.2564e-01,  7.2067e-02],
         [ 1.3359e+00, -1.1488e-01,  6.2638e-01,  1.4322e+00, -1.7506e+00],
         [-2.8810e-01,  1.8320e+00,  3.6360e-01, -7.1135e-01, -1.1935e-02],
         [-5.6708e-01, -1.5625e-01, -9.3625e-02, -9.5858e-01, -1.1692e+00],
         [ 9.9512e-02, -2.3570e-01, -3.7029e-01, -1.9683e-01,  6.5943e-01]],

        [[-7.5461e-02,  8.7807e-01,  7.9787e-02,  1.3164e+00,  3.2281e-02],
         [ 9.0863e-01

In [32]:
weights_aligned = weights_named.align_as(img_named)  #weights_named原為1軸張量, 變成1個3軸張量
print(weights_aligned.shape, weights_aligned.names)
print(weights_aligned)     #張量擴張

torch.Size([3, 1, 1]) ('channels', 'rows', 'columns')
tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))


In [33]:
gray_named = (img_named * weights_aligned)
print(gray_named)
gray_named_sum = gray_named.sum('channels')
print(gray_named_sum)
print(gray_named_sum.shape, gray_named_sum.names)

tensor([[[-9.9789e-02,  4.0120e-02, -4.0092e-02, -1.8672e-01,  2.9815e-01],
         [ 1.3126e-01, -1.5107e-01,  4.2414e-02,  2.4347e-01,  4.2732e-05],
         [ 3.1625e-02, -5.2250e-02,  2.4513e-01, -1.9939e-01, -5.3641e-01],
         [ 1.8093e-03,  2.3890e-02, -4.1412e-01,  5.9259e-02, -5.4248e-01],
         [ 7.2494e-02,  4.1549e-01,  6.7236e-01,  2.4636e-01, -5.0494e-01]],

        [[-4.8714e-01, -1.2266e+00,  1.1842e+00,  3.0442e-01,  5.1542e-02],
         [ 9.5546e-01, -8.2159e-02,  4.4799e-01,  1.0243e+00, -1.2520e+00],
         [-2.0605e-01,  1.3102e+00,  2.6004e-01, -5.0876e-01, -8.5358e-03],
         [-4.0558e-01, -1.1175e-01, -6.6961e-02, -6.8558e-01, -8.3625e-01],
         [ 7.1171e-02, -1.6857e-01, -2.6483e-01, -1.4077e-01,  4.7163e-01]],

        [[-5.4483e-03,  6.3397e-02,  5.7606e-03,  9.5045e-02,  2.3307e-03],
         [ 6.5603e-02,  3.1952e-02,  5.1608e-03,  6.2442e-02,  7.7536e-02],
         [ 6.1868e-02, -2.0491e-02, -2.1826e-02,  3.3459e-02, -2.1245e-03],
        

In [34]:
double_points = torch.ones(10, 2, dtype = torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype = torch.short)
short_points.dtype

torch.int16

In [35]:
double_points = torch.zeros(10, 2).double()
print(double_points.dtype)

torch.float64


In [36]:
double_points = torch.zeros(10, 2)
double_points = double_points.to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
print(double_points.dtype)
print(short_points.dtype)

torch.float64
torch.int16


In [37]:
points_64 = torch.zeros(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [38]:
#用torch
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [39]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [43]:
import torch
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [44]:
points_storage = points.storage()
points_storage[5]

1.0

In [45]:
points.storage()[2]

5.0

In [46]:
points_storage[3] = 10.3
points

tensor([[ 4.0000,  1.0000],
        [ 5.0000, 10.3000],
        [ 2.0000,  1.0000]])

In [47]:
a = torch.ones(3, 2)
print(a)
a.zero_()
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [48]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [49]:
second_point = points[1]
second_point.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [50]:
second_point.storage_offset()

2

In [51]:
second_point.size()

torch.Size([2])

In [52]:
second_point

tensor([5., 3.])

In [53]:
second_point.shape

torch.Size([2])

In [54]:
points.stride()

(2, 1)

In [55]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [56]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()       #複製新的避免母張量被更改
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [57]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [58]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [59]:
id(points.storage()) == id(points_t.storage())

False

In [60]:
points.stride()

(2, 1)

In [61]:
points_t.stride()

(1, 2)

In [62]:
points.is_contiguous()

True

In [63]:
points_t.is_contiguous()

False

In [64]:
some_t = torch.ones(3, 4, 5)
some_t.shape

torch.Size([3, 4, 5])

In [65]:
transpose_t = some_t.transpose(0, 2)
transpose_t.shape

torch.Size([5, 4, 3])

In [66]:
some_t.stride()

(20, 5, 1)

In [67]:
transpose_t.stride()

(1, 5, 20)

In [69]:
print(points.is_contiguous())
points.contiguous()
print(points_t.is_contiguous())

True
False


In [72]:
print(torch.__version__)
print(torch.cuda.is_available())
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
print(points_gpu)

1.11.0
True
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')


In [73]:
points_gpu = points.to(device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [74]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_gpu = points.cpu()

In [77]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [78]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])